"""add_pipelines_and_context_cache

Revision ID: 3ae3c9042341
Revises: 707c7b81b3c2
Create Date: 2026-04-08 20:47:20.133104

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3ae3c9042341'
down_revision: Union[str, Sequence[str], None] = '707c7b81b3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
