"""add_indexes_and_preferred_model

Revision ID: 74d734fbdf07
Revises: b8e4c0d23f56
Create Date: 2026-04-12 22:39:31.497834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74d734fbdf07'
down_revision: Union[str, Sequence[str], None] = 'b8e4c0d23f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_sessions', sa.Column('preferred_model', sa.String(length=50), nullable=True))
    op.create_index('ix_active_sessions_user_channel', 'active_sessions', ['user_id', 'channel'], unique=False)
    op.create_index('ix_channel_identities_lookup', 'channel_identities', ['channel', 'channel_user_id'], unique=True)
    op.alter_column('deployments', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index('ix_messages_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_omni_instances_company_id'), table_name='omni_instances')
    op.alter_column('templates', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('templates', 'architecture_bullets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('templates', 'env_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('templates', 'changelog',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(op.f('templates_slug_key'), 'templates', type_='unique')
    op.create_index('ix_threads_user_pipeline_active', 'threads', ['user_id', 'pipeline_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_user_pipeline_active', table_name='threads')
    op.create_unique_constraint(op.f('templates_slug_key'), 'templates', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('templates', 'changelog',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('templates', 'env_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('templates', 'architecture_bullets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('templates', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_omni_instances_company_id'), 'omni_instances', ['company_id'], unique=False)
    op.drop_index('ix_messages_thread_created', table_name='messages')
    op.alter_column('deployments', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index('ix_channel_identities_lookup', table_name='channel_identities')
    op.drop_index('ix_active_sessions_user_channel', table_name='active_sessions')
    op.drop_column('active_sessions', 'preferred_model')
    # ### end Alembic commands ###
